const chosenIntervals = id => {
	currentInterval = document.querySelector(`[data-Int-id=${id}]`);
	if (currentNote.value === 'C' && currentInterval.value === 'm2') show_interval('C#');
	if (currentNote.value === 'C' && currentInterval.value === 'M2') show_interval('D');
	if (currentNote.value === 'C' && currentInterval.value === 'm3') show_interval('D#');
	if (currentNote.value === 'C' && currentInterval.value === 'M3') show_interval('E');
	if (currentNote.value === 'C' && currentInterval.value === 'p4') show_interval('F');
	if (currentNote.value === 'C' && currentInterval.value === 'TT') show_interval('F#');
	if (currentNote.value === 'C' && currentInterval.value === 'p5') show_interval('G');
	if (currentNote.value === 'C' && currentInterval.value === 'm6') show_interval('G#');
	if (currentNote.value === 'C' && currentInterval.value === 'M6') show_interval('A');
	if (currentNote.value === 'C' && currentInterval.value === 'm7') show_interval('A#');
	if (currentNote.value === 'C' && currentInterval.value === 'M7') show_interval('B');

	if (currentNote.value === 'C#' && currentInterval.value === 'm2') show_interval('D');
	if (currentNote.value === 'C#' && currentInterval.value === 'M2') show_interval('D#');
	if (currentNote.value === 'C#' && currentInterval.value === 'm3') show_interval('E');
	if (currentNote.value === 'C#' && currentInterval.value === 'M3') show_interval('F');
	if (currentNote.value === 'C#' && currentInterval.value === 'p4') show_interval('F#');
	if (currentNote.value === 'C#' && currentInterval.value === 'TT') show_interval('G');
	if (currentNote.value === 'C#' && currentInterval.value === 'p5') show_interval('G#');
	if (currentNote.value === 'C#' && currentInterval.value === 'm6') show_interval('A');
	if (currentNote.value === 'C#' && currentInterval.value === 'M6') show_interval('A#');
	if (currentNote.value === 'C#' && currentInterval.value === 'm7') show_interval('B');
	if (currentNote.value === 'C#' && currentInterval.value === 'M7') show_interval('C');

	if (currentNote.value === 'D' && currentInterval.value === 'm2') show_interval('D#');
	if (currentNote.value === 'D' && currentInterval.value === 'M2') show_interval('E');
	if (currentNote.value === 'D' && currentInterval.value === 'm3') show_interval('F');
	if (currentNote.value === 'D' && currentInterval.value === 'M3') show_interval('F#');
	if (currentNote.value === 'D' && currentInterval.value === 'p4') show_interval('G');
	if (currentNote.value === 'D' && currentInterval.value === 'TT') show_interval('G#');
	if (currentNote.value === 'D' && currentInterval.value === 'p5') show_interval('A');
	if (currentNote.value === 'D' && currentInterval.value === 'm6') show_interval('A#');
	if (currentNote.value === 'D' && currentInterval.value === 'M6') show_interval('B');
	if (currentNote.value === 'D' && currentInterval.value === 'm7') show_interval('C');
	if (currentNote.value === 'D' && currentInterval.value === 'M7') show_interval('C#');
	////
	if (currentNote.value === 'D#' && currentInterval.value === 'm2') show_interval('E');
	if (currentNote.value === 'D#' && currentInterval.value === 'M2') show_interval('F');
	if (currentNote.value === 'D#' && currentInterval.value === 'm3') show_interval('F#');
	if (currentNote.value === 'D#' && currentInterval.value === 'M3') show_interval('G');
	if (currentNote.value === 'D#' && currentInterval.value === 'p4') show_interval('G#');
	if (currentNote.value === 'D#' && currentInterval.value === 'TT') show_interval('A');
	if (currentNote.value === 'D#' && currentInterval.value === 'p5') show_interval('A#');
	if (currentNote.value === 'D#' && currentInterval.value === 'm6') show_interval('B');
	if (currentNote.value === 'D#' && currentInterval.value === 'M6') show_interval('C');
	if (currentNote.value === 'D#' && currentInterval.value === 'm7') show_interval('C#');
	if (currentNote.value === 'D#' && currentInterval.value === 'M7') show_interval('D');

	if (currentNote.value === 'E' && currentInterval.value === 'm2') show_interval('F');
	if (currentNote.value === 'E' && currentInterval.value === 'M2') show_interval('F#');
	if (currentNote.value === 'E' && currentInterval.value === 'm3') show_interval('G');
	if (currentNote.value === 'E' && currentInterval.value === 'M3') show_interval('G#');
	if (currentNote.value === 'E' && currentInterval.value === 'p4') show_interval('A');
	if (currentNote.value === 'E' && currentInterval.value === 'TT') show_interval('A#');
	if (currentNote.value === 'E' && currentInterval.value === 'p5') show_interval('B');
	if (currentNote.value === 'E' && currentInterval.value === 'm6') show_interval('C');
	if (currentNote.value === 'E' && currentInterval.value === 'M6') show_interval('C#');
	if (currentNote.value === 'E' && currentInterval.value === 'm7') show_interval('D');
	if (currentNote.value === 'E' && currentInterval.value === 'M7') show_interval('D#');

	if (currentNote.value === 'F' && currentInterval.value === 'm2') show_interval('F#');
	if (currentNote.value === 'F' && currentInterval.value === 'M2') show_interval('G');
	if (currentNote.value === 'F' && currentInterval.value === 'm3') show_interval('G#');
	if (currentNote.value === 'F' && currentInterval.value === 'M3') show_interval('A');
	if (currentNote.value === 'F' && currentInterval.value === 'p4') show_interval('A#');
	if (currentNote.value === 'F' && currentInterval.value === 'TT') show_interval('B');
	if (currentNote.value === 'F' && currentInterval.value === 'p5') show_interval('C');
	if (currentNote.value === 'F' && currentInterval.value === 'm6') show_interval('C#');
	if (currentNote.value === 'F' && currentInterval.value === 'M6') show_interval('D');
	if (currentNote.value === 'F' && currentInterval.value === 'm7') show_interval('D#');
	if (currentNote.value === 'F' && currentInterval.value === 'M7') show_interval('E');

	if (currentNote.value === 'F#' && currentInterval.value === 'm2') show_interval('G');
	if (currentNote.value === 'F#' && currentInterval.value === 'M2') show_interval('G#');
	if (currentNote.value === 'F#' && currentInterval.value === 'm3') show_interval('A');
	if (currentNote.value === 'F#' && currentInterval.value === 'M3') show_interval('A#');
	if (currentNote.value === 'F#' && currentInterval.value === 'p4') show_interval('B');
	if (currentNote.value === 'F#' && currentInterval.value === 'TT') show_interval('C');
	if (currentNote.value === 'F#' && currentInterval.value === 'p5') show_interval('C#');
	if (currentNote.value === 'F#' && currentInterval.value === 'm6') show_interval('D');
	if (currentNote.value === 'F#' && currentInterval.value === 'M6') show_interval('D#');
	if (currentNote.value === 'F#' && currentInterval.value === 'm7') show_interval('E');
	if (currentNote.value === 'F#' && currentInterval.value === 'M7') show_interval('F');

	if (currentNote.value === 'G' && currentInterval.value === 'm2') show_interval('G#');
	if (currentNote.value === 'G' && currentInterval.value === 'M2') show_interval('A');
	if (currentNote.value === 'G' && currentInterval.value === 'm3') show_interval('A#');
	if (currentNote.value === 'G' && currentInterval.value === 'M3') show_interval('B');
	if (currentNote.value === 'G' && currentInterval.value === 'p4') show_interval('C');
	if (currentNote.value === 'G' && currentInterval.value === 'TT') show_interval('C#');
	if (currentNote.value === 'G' && currentInterval.value === 'p5') show_interval('D');
	if (currentNote.value === 'G' && currentInterval.value === 'm6') show_interval('D#');
	if (currentNote.value === 'G' && currentInterval.value === 'M6') show_interval('E');
	if (currentNote.value === 'G' && currentInterval.value === 'm7') show_interval('F');
	if (currentNote.value === 'G' && currentInterval.value === 'M7') show_interval('F#');

	if (currentNote.value === 'G#' && currentInterval.value === 'm2') show_interval('A');
	if (currentNote.value === 'G#' && currentInterval.value === 'M2') show_interval('A#');
	if (currentNote.value === 'G#' && currentInterval.value === 'm3') show_interval('B');
	if (currentNote.value === 'G#' && currentInterval.value === 'M3') show_interval('C');
	if (currentNote.value === 'G#' && currentInterval.value === 'p4') show_interval('C#');
	if (currentNote.value === 'G#' && currentInterval.value === 'TT') show_interval('D');
	if (currentNote.value === 'G#' && currentInterval.value === 'p5') show_interval('D#');
	if (currentNote.value === 'G#' && currentInterval.value === 'm6') show_interval('E');
	if (currentNote.value === 'G#' && currentInterval.value === 'M6') show_interval('F');
	if (currentNote.value === 'G#' && currentInterval.value === 'm7') show_interval('F#');
	if (currentNote.value === 'G#' && currentInterval.value === 'M7') show_interval('G');

	if (currentNote.value === 'A' && currentInterval.value === 'm2') show_interval('A#');
	if (currentNote.value === 'A' && currentInterval.value === 'M2') show_interval('B');
	if (currentNote.value === 'A' && currentInterval.value === 'm3') show_interval('C');
	if (currentNote.value === 'A' && currentInterval.value === 'M3') show_interval('C#');
	if (currentNote.value === 'A' && currentInterval.value === 'p4') show_interval('D');
	if (currentNote.value === 'A' && currentInterval.value === 'TT') show_interval('D#');
	if (currentNote.value === 'A' && currentInterval.value === 'p5') show_interval('E');
	if (currentNote.value === 'A' && currentInterval.value === 'm6') show_interval('F');
	if (currentNote.value === 'A' && currentInterval.value === 'M6') show_interval('F#');
	if (currentNote.value === 'A' && currentInterval.value === 'm7') show_interval('G');
	if (currentNote.value === 'A' && currentInterval.value === 'M7') show_interval('G#');

	if (currentNote.value === 'A#' && currentInterval.value === 'm2') show_interval('B');
	if (currentNote.value === 'A#' && currentInterval.value === 'M2') show_interval('C');
	if (currentNote.value === 'A#' && currentInterval.value === 'm3') show_interval('C#');
	if (currentNote.value === 'A#' && currentInterval.value === 'M3') show_interval('D');
	if (currentNote.value === 'A#' && currentInterval.value === 'p4') show_interval('D#');
	if (currentNote.value === 'A#' && currentInterval.value === 'TT') show_interval('E');
	if (currentNote.value === 'A#' && currentInterval.value === 'p5') show_interval('F');
	if (currentNote.value === 'A#' && currentInterval.value === 'm6') show_interval('F#');
	if (currentNote.value === 'A#' && currentInterval.value === 'M6') show_interval('G');
	if (currentNote.value === 'A#' && currentInterval.value === 'm7') show_interval('G#');
	if (currentNote.value === 'A#' && currentInterval.value === 'M7') show_interval('A');

	if (currentNote.value === 'B' && currentInterval.value === 'm2') show_interval('C');
	if (currentNote.value === 'B' && currentInterval.value === 'M2') show_interval('C#');
	if (currentNote.value === 'B' && currentInterval.value === 'm3') show_interval('D');
	if (currentNote.value === 'B' && currentInterval.value === 'M3') show_interval('D#');
	if (currentNote.value === 'B' && currentInterval.value === 'p4') show_interval('E');
	if (currentNote.value === 'B' && currentInterval.value === 'TT') show_interval('F');
	if (currentNote.value === 'B' && currentInterval.value === 'p5') show_interval('F#');
	if (currentNote.value === 'B' && currentInterval.value === 'm6') show_interval('G');
	if (currentNote.value === 'B' && currentInterval.value === 'M6') show_interval('G#');
	if (currentNote.value === 'B' && currentInterval.value === 'm7') show_interval('A');
	if (currentNote.value === 'B' && currentInterval.value === 'M7') show_interval('A#');
};
